# Builder
FROM node:18.4-alpine AS builder
LABEL node-builder=1
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Runner
FROM nginx:stable-alpine as runner
LABEL react-runner=1
COPY --from=builder /app/dist /usr/share/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]