# Builder
FROM node:18.4 AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Runner
FROM nginx:stable-alpine as runner
COPY --from=builder /app/dist /usr/share/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]