import { useMemo } from 'react';
import ReactFlow, { Controls } from 'reactflow';
import 'reactflow/dist/style.css';
import { DetailWrapper } from './FERoadmap';
import CommonNode from './node-style/CommonNode';

const nodes = [
  {
    width: 160,
    height: 42,
    id: '1',
    position: { x: 280, y: 50 },
    data: { label: 'Rust' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '2',
    position: { x: 280, y: 110 },
    data: { label: 'Go' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '3',
    position: { x: 520, y: 50 },
    data: { label: 'Java' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '4',
    position: { x: 520, y: 110 },
    data: { label: 'C#' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '5',
    position: { x: 520, y: 170 },
    data: { label: 'PHP' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '6',
    position: { x: 750, y: 50 },
    data: { label: 'JavaScript' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '7',
    position: { x: 750, y: 110 },
    data: { label: 'Python' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '8',
    position: { x: 750, y: 170 },
    data: { label: 'Ruby' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '9',
    position: { x: 140, y: 270 },
    data: { label: '관계형 데이터베이스' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '10-1',
    position: { x: 60, y: 330 },
    data: { label: 'PostgreSQL' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '10-2',
    position: { x: 60, y: 380 },
    data: { label: 'MySQL' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '10-3',
    position: { x: 60, y: 430 },
    data: { label: 'MariaDB' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '10-4',
    position: { x: 220, y: 330 },
    data: { label: 'MS SQL' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '10-5',
    position: { x: 220, y: 380 },
    data: { label: 'Oracle' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '11',
    position: { x: 520, y: 270 },
    data: { label: 'NoSQL 데이터베이스' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '12-1',
    position: { x: 440, y: 330 },
    data: { label: 'MongoDB' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '12-2',
    position: { x: 440, y: 380 },
    data: { label: 'RethinkDB' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '12-3',
    position: { x: 600, y: 330 },
    data: { label: 'CouchDB' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '12-4',
    position: { x: 600, y: 380 },
    data: { label: 'DynamoDB' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '13',
    position: { x: 900, y: 270 },
    data: { label: '데이터베이스 심화' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '14-1',
    position: { x: 820, y: 330 },
    data: { label: 'ORMs' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '14-2',
    position: { x: 820, y: 380 },
    data: { label: 'ACID' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '14-3',
    position: { x: 820, y: 430 },
    data: { label: '트랜잭션' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '14-4',
    position: { x: 980, y: 330 },
    data: { label: 'N+1 문제' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '14-5',
    position: { x: 980, y: 380 },
    data: { label: '데이터베이스 정규화' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '14-6',
    position: { x: 980, y: 430 },
    data: { label: 'Index와 동작 방식' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '15',
    position: { x: 320, y: 530 },
    data: { label: '로그인' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-1',
    position: { x: 240, y: 590 },
    data: { label: 'Cookie 기반' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-2',
    position: { x: 240, y: 640 },
    data: { label: 'OAuth' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-3',
    position: { x: 240, y: 690 },
    data: { label: '기본 인증' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-4',
    position: { x: 240, y: 740 },
    data: { label: '토큰 기반 인증' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-5',
    position: { x: 400, y: 590 },
    data: { label: 'JWT' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-6',
    position: { x: 400, y: 640 },
    data: { label: 'OpenID' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-7',
    position: { x: 400, y: 690 },
    data: { label: 'SAML' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '17',
    position: { x: 720, y: 530 },
    data: { label: 'APIs' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '18-1',
    position: { x: 640, y: 590 },
    data: { label: 'HATEOAS' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '18-2',
    position: { x: 640, y: 640 },
    data: { label: 'Open API와 Swagger' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '18-3',
    position: { x: 640, y: 690 },
    data: { label: '인증' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '18-4',
    position: { x: 800, y: 590 },
    data: { label: 'REST' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '18-5',
    position: { x: 800, y: 640 },
    data: { label: 'JSON APIs' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '18-6',
    position: { x: 800, y: 690 },
    data: { label: 'SOAP' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '19',
    position: { x: 320, y: 840 },
    data: { label: '캐싱' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '20',
    position: { x: 520, y: 840 },
    data: { label: '테스팅' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '21',
    position: { x: 720, y: 840 },
    data: { label: '웹 보안 지식' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22',
    position: { x: 320, y: 940 },
    data: { label: '디자인과 개발 원칙' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22-1',
    position: { x: 240, y: 1000 },
    data: { label: 'GOF 디자인 패턴' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22-2',
    position: { x: 240, y: 1050 },
    data: { label: '도메인 주도 설계' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22-3',
    position: { x: 240, y: 1100 },
    data: { label: '테스트 주도 개발' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22-4',
    position: { x: 400, y: 1000 },
    data: { label: 'SOLID' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22-5',
    position: { x: 400, y: 1050 },
    data: { label: 'KISS' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22-6',
    position: { x: 400, y: 1100 },
    data: { label: 'YAGNI' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '22-7',
    position: { x: 400, y: 1150 },
    data: { label: 'DRY' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '23',
    position: { x: 720, y: 940 },
    data: { label: '아키텍처 패턴' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '24-1',
    position: { x: 640, y: 1000 },
    data: { label: '모놀리식 애플리케이션' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '24-2',
    position: { x: 640, y: 1050 },
    data: { label: '마이크로서비스' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '24-3',
    position: { x: 640, y: 1100 },
    data: { label: 'SOA' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '24-4',
    position: { x: 800, y: 1000 },
    data: { label: 'CQRS와 이벤트 소싱' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '24-5',
    position: { x: 800, y: 1050 },
    data: { label: '서버리스' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '25',
    position: { x: 320, y: 1250 },
    data: { label: 'Search Engine' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '26-1',
    position: { x: 320, y: 1310 },
    data: { label: '일래스틱서치' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '26-2',
    position: { x: 320, y: 1360 },
    data: { label: 'Solr' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '27',
    position: { x: 520, y: 1250 },
    data: { label: '메시지 브로커' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '28-1',
    position: { x: 520, y: 1310 },
    data: { label: 'RabbitMQ' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '28-2',
    position: { x: 520, y: 1360 },
    data: { label: 'Kafka' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '29',
    position: { x: 720, y: 1250 },
    data: { label: '가상화' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '30',
    position: { x: 720, y: 1310 },
    data: { label: 'Docker' },
    type: 'default',
  },
];

const edges = [
  {
    source: '9',
    sourceHandle: 'b',
    target: '10-1',
    targetHandle: 't',
    id: 'reactflow__edge-9b-10-1t',
    selected: false,
  },
  {
    source: '10-1',
    sourceHandle: 'b',
    target: '10-2',
    targetHandle: 't',
    id: 'reactflow__edge-10-1b-10-2t',
    selected: false,
  },
  {
    source: '10-2',
    sourceHandle: 'b',
    target: '10-3',
    targetHandle: 't',
    id: 'reactflow__edge-10-2b-10-3t',
    selected: false,
  },
  {
    source: '9',
    sourceHandle: 'b',
    target: '10-4',
    targetHandle: 't',
    id: 'reactflow__edge-9b-10-4t',
    selected: false,
  },
  {
    source: '10-4',
    sourceHandle: 'b',
    target: '10-5',
    targetHandle: 't',
    id: 'reactflow__edge-10-4b-10-5t',
    selected: false,
  },
  {
    source: '11',
    sourceHandle: 'b',
    target: '12-1',
    targetHandle: 't',
    id: 'reactflow__edge-11b-12-1t',
    selected: false,
  },
  {
    source: '12-1',
    sourceHandle: 'b',
    target: '12-2',
    targetHandle: 't',
    id: 'reactflow__edge-12-1b-12-2t',
    selected: false,
  },
  {
    source: '11',
    sourceHandle: 'b',
    target: '12-3',
    targetHandle: 't',
    id: 'reactflow__edge-9b-12-3t',
    selected: false,
  },
  {
    source: '12-3',
    sourceHandle: 'b',
    target: '12-4',
    targetHandle: 't',
    id: 'reactflow__edge-12-3b-12-4t',
    selected: false,
  },
  {
    source: '13',
    sourceHandle: 'b',
    target: '14-1',
    targetHandle: 't',
    id: 'reactflow__edge-13b-14-1t',
    selected: false,
  },
  {
    source: '14-1',
    sourceHandle: 'b',
    target: '14-2',
    targetHandle: 't',
    id: 'reactflow__edge-14-1b-14-2t',
    selected: false,
  },
  {
    source: '14-2',
    sourceHandle: 'b',
    target: '14-3',
    targetHandle: 't',
    id: 'reactflow__edge-14-2b-14-3t',
    selected: false,
  },
  {
    source: '13',
    sourceHandle: 'b',
    target: '14-4',
    targetHandle: 't',
    id: 'reactflow__edge-13b-14-4t',
    selected: false,
  },
  {
    source: '14-4',
    sourceHandle: 'b',
    target: '14-5',
    targetHandle: 't',
    id: 'reactflow__edge-14-4b-14-5t',
    selected: false,
  },
  {
    source: '14-5',
    sourceHandle: 'b',
    target: '14-6',
    targetHandle: 't',
    id: 'reactflow__edge-14-5b-14-6t',
    selected: false,
  },
  {
    source: '15',
    sourceHandle: 'b',
    target: '16-1',
    targetHandle: 't',
    id: 'reactflow__edge-15b-16-1t',
    selected: false,
  },
  {
    source: '16-1',
    sourceHandle: 'b',
    target: '16-2',
    targetHandle: 't',
    id: 'reactflow__edge-16-1b-16-2t',
    selected: false,
  },
  {
    source: '16-2',
    sourceHandle: 'b',
    target: '16-3',
    targetHandle: 't',
    id: 'reactflow__edge-16-2b-16-3t',
    selected: false,
  },
  {
    source: '16-3',
    sourceHandle: 'b',
    target: '16-4',
    targetHandle: 't',
    id: 'reactflow__edge-16-3b-16-4t',
    selected: false,
  },
  {
    source: '15',
    sourceHandle: 'b',
    target: '16-5',
    targetHandle: 't',
    id: 'reactflow__edge-15b-16-5t',
    selected: false,
  },
  {
    source: '16-5',
    sourceHandle: 'b',
    target: '16-6',
    targetHandle: 't',
    id: 'reactflow__edge-16-5b-16-6t',
    selected: false,
  },
  {
    source: '16-6',
    sourceHandle: 'b',
    target: '16-7',
    targetHandle: 't',
    id: 'reactflow__edge-16-6b-16-7t',
    selected: false,
  },
  {
    source: '17',
    sourceHandle: 'b',
    target: '18-1',
    targetHandle: 't',
    id: 'reactflow__edge-17b-18-1t',
    selected: false,
  },
  {
    source: '18-1',
    sourceHandle: 'b',
    target: '18-2',
    targetHandle: 't',
    id: 'reactflow__edge-18-1b-18-2t',
    selected: false,
  },
  {
    source: '18-2',
    sourceHandle: 'b',
    target: '18-3',
    targetHandle: 't',
    id: 'reactflow__edge-18-2b-18-3t',
    selected: false,
  },
  {
    source: '17',
    sourceHandle: 'b',
    target: '18-4',
    targetHandle: 't',
    id: 'reactflow__edge-17b-18-4t',
    selected: false,
  },
  {
    source: '18-4',
    sourceHandle: 'b',
    target: '18-5',
    targetHandle: 't',
    id: 'reactflow__edge-18-4b-18-5t',
    selected: false,
  },
  {
    source: '18-5',
    sourceHandle: 'b',
    target: '18-6',
    targetHandle: 't',
    id: 'reactflow__edge-18-5b-18-6t',
    selected: false,
  },
  {
    source: '22',
    sourceHandle: 'b',
    target: '22-1',
    targetHandle: 't',
    id: 'reactflow__edge-22b-22-1t',
    selected: false,
  },
  {
    source: '22-1',
    sourceHandle: 'b',
    target: '22-2',
    targetHandle: 't',
    id: 'reactflow__edge-22-1b-22-2t',
    selected: false,
  },
  {
    source: '22-2',
    sourceHandle: 'b',
    target: '22-3',
    targetHandle: 't',
    id: 'reactflow__edge-22-2b-22-3t',
    selected: false,
  },
  {
    source: '22',
    sourceHandle: 'b',
    target: '22-4',
    targetHandle: 't',
    id: 'reactflow__edge-22b-22-4t',
    selected: false,
  },
  {
    source: '22-4',
    sourceHandle: 'b',
    target: '22-5',
    targetHandle: 't',
    id: 'reactflow__edge-22-4b-22-5t',
    selected: false,
  },
  {
    source: '22-5',
    sourceHandle: 'b',
    target: '22-6',
    targetHandle: 't',
    id: 'reactflow__edge-22-5b-22-6t',
    selected: false,
  },
  {
    source: '22-6',
    sourceHandle: 'b',
    target: '22-7',
    targetHandle: 't',
    id: 'reactflow__edge-22-6b-22-7t',
    selected: false,
  },
  {
    source: '23',
    sourceHandle: 'b',
    target: '24-1',
    targetHandle: 't',
    id: 'reactflow__edge-23b-24-1t',
    selected: false,
  },
  {
    source: '24-1',
    sourceHandle: 'b',
    target: '24-2',
    targetHandle: 't',
    id: 'reactflow__edge-24-1b-24-2t',
    selected: false,
  },
  {
    source: '24-2',
    sourceHandle: 'b',
    target: '24-3',
    targetHandle: 't',
    id: 'reactflow__edge-24-2b-24-3t',
    selected: false,
  },
  {
    source: '23',
    sourceHandle: 'b',
    target: '24-4',
    targetHandle: 't',
    id: 'reactflow__edge-23b-24-4t',
    selected: false,
  },
  {
    source: '24-4',
    sourceHandle: 'b',
    target: '24-5',
    targetHandle: 't',
    id: 'reactflow__edge-24-4b-24-5t',
    selected: false,
  },
  {
    source: '25',
    sourceHandle: 'b',
    target: '26-1',
    targetHandle: 't',
    id: 'reactflow__edge-25b-26-1t',
    selected: false,
  },
  {
    source: '26-1',
    sourceHandle: 'b',
    target: '26-2',
    targetHandle: 't',
    id: 'reactflow__edge-26-1b-26-2t',
    selected: false,
  },
  {
    source: '27',
    sourceHandle: 'b',
    target: '28-1',
    targetHandle: 't',
    id: 'reactflow__edge-27b-28-1t',
    selected: false,
  },
  {
    source: '28-1',
    sourceHandle: 'b',
    target: '28-2',
    targetHandle: 't',
    id: 'reactflow__edge-28-1b-28-2t',
    selected: false,
  },
  {
    source: '29',
    sourceHandle: 'b',
    target: '30',
    targetHandle: 't',
    id: 'reactflow__edge-29b-30t',
    selected: false,
  },
];

const BERoadmap = () => {
  const nodeTypes = useMemo(() => ({ default: CommonNode }), []);

  return (
    <DetailWrapper>
      <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView>
        <Controls />
      </ReactFlow>
    </DetailWrapper>
  );
};

export default BERoadmap;
