import { useMemo } from 'react';
import ReactFlow, { Controls } from 'reactflow';
import 'reactflow/dist/style.css';
import styled from 'styled-components';
import CommonNode from './node-style/CommonNode';

const nodes = [
  {
    width: 160,
    height: 42,
    id: '1-1',
    position: { x: 520, y: 50 },
    data: { label: 'HTML' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '1-2',
    position: { x: 520, y: 110 },
    data: { label: 'CSS' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '1-3',
    position: { x: 520, y: 170 },
    data: { label: 'JavaScript' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '2',
    position: { x: 290, y: 110 },
    data: { label: 'BEM' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '3-1',
    position: { x: 750, y: 110 },
    data: { label: 'Sass' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '3-2',
    position: { x: 750, y: 170 },
    data: { label: 'PostCSS' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '3-3',
    position: { x: 750, y: 230 },
    data: { label: 'cssnext' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '4-1',
    position: { x: 290, y: 230 },
    data: { label: 'Webpack' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '4-2',
    position: { x: 290, y: 290 },
    data: { label: 'Rollup' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '4-3',
    position: { x: 290, y: 350 },
    data: { label: 'Parcel' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '5-1',
    position: { x: 750, y: 350 },
    data: { label: 'Prettier' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '5-2',
    position: { x: 750, y: 410 },
    data: { label: 'ESLint' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '6',
    position: { x: 120, y: 530 },
    data: { label: 'React' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '7',
    position: { x: 520, y: 530 },
    data: { label: 'Vue' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '8',
    position: { x: 920, y: 530 },
    data: { label: 'Angular' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '9-1',
    position: { x: 20, y: 590 },
    data: { label: 'Redux' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '9-2',
    position: { x: 20, y: 650 },
    data: { label: 'Recoil' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '10',
    position: { x: 220, y: 590 },
    data: { label: 'Next.js' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '11',
    position: { x: 420, y: 590 },
    data: { label: 'VueX' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '12',
    position: { x: 620, y: 590 },
    data: { label: 'Nuxt.js' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '13-1',
    position: { x: 820, y: 590 },
    data: { label: 'RxJS' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '13-2',
    position: { x: 820, y: 650 },
    data: { label: 'NgRx' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '14',
    position: { x: 1020, y: 590 },
    data: { label: 'Universal' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '15-1',
    position: { x: 290, y: 770 },
    data: { label: 'Styled Components' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '15-2',
    position: { x: 290, y: 830 },
    data: { label: 'CSS Modules' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '15-3',
    position: { x: 290, y: 890 },
    data: { label: 'Styled JSX' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '15-4',
    position: { x: 290, y: 950 },
    data: { label: 'Emotion' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-1',
    position: { x: 520, y: 770 },
    data: { label: 'Reactstra' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-2',
    position: { x: 520, y: 830 },
    data: { label: 'MUI' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-3',
    position: { x: 520, y: 890 },
    data: { label: 'Tailwind CSS' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '16-4',
    position: { x: 520, y: 950 },
    data: { label: 'Chakra UI' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '17-1',
    position: { x: 750, y: 770 },
    data: { label: 'Bootstrap' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '17-2',
    position: { x: 750, y: 830 },
    data: { label: 'Materialize CSS' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '17-3',
    position: { x: 750, y: 890 },
    data: { label: 'Bulma' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '18',
    position: { x: 290, y: 1070 },
    data: { label: 'GraphQL' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '19-1',
    position: { x: 190, y: 1130 },
    data: { label: 'Apollo' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '19-2',
    position: { x: 390, y: 1130 },
    data: { label: 'Relay Mode' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '20',
    position: { x: 750, y: 1070 },
    data: { label: 'Mobile' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '21-1',
    position: { x: 650, y: 1130 },
    data: { label: 'React Native' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '21-2',
    position: { x: 650, y: 1190 },
    data: { label: 'NativeScript' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '21-3',
    position: { x: 840, y: 1130 },
    data: { label: 'Flutter' },
    type: 'default',
  },
  {
    width: 160,
    height: 42,
    id: '21-4',
    position: { x: 840, y: 1190 },
    data: { label: 'Ionic' },
    type: 'default',
  },
];

const edges = [
  {
    source: '1-1',
    sourceHandle: 'b',
    target: '1-2',
    targetHandle: 't',
    id: 'reactflow__edge-1-1b-1-2t',
    selected: false,
  },
  {
    source: '1-2',
    sourceHandle: 'b',
    target: '1-3',
    targetHandle: 't',
    id: 'reactflow__edge-1-2b-1-3t',
    selected: false,
  },
  {
    source: '3-1',
    sourceHandle: 'b',
    target: '3-2',
    targetHandle: 't',
    id: 'reactflow__edge-3-1b-3-2t',
    selected: false,
  },
  {
    source: '3-2',
    sourceHandle: 'b',
    target: '3-3',
    targetHandle: 't',
    id: 'reactflow__edge-3-2b-3-3t',
    selected: false,
  },
  {
    source: '4-1',
    sourceHandle: 'b',
    target: '4-2',
    targetHandle: 't',
    id: 'reactflow__edge-4-1b-4-2t',
    selected: false,
  },
  {
    source: '4-2',
    sourceHandle: 'b',
    target: '4-3',
    targetHandle: 't',
    id: 'reactflow__edge-4-2b-4-3t',
    selected: false,
  },
  {
    source: '5-1',
    sourceHandle: 'b',
    target: '5-2',
    targetHandle: 't',
    id: 'reactflow__edge-5-1b-5-2t',
    selected: false,
  },
  {
    source: '1-3',
    sourceHandle: 'b',
    target: '6',
    targetHandle: 't',
    id: 'reactflow__edge-1-3b-6t',
    selected: false,
  },
  {
    source: '1-3',
    sourceHandle: 'b',
    target: '7',
    targetHandle: 't',
    id: 'reactflow__edge-1-3b-7t',
    selected: false,
  },
  {
    source: '1-3',
    sourceHandle: 'b',
    target: '8',
    targetHandle: 't',
    id: 'reactflow__edge-1-3b-8t',
    selected: false,
  },
  {
    source: '6',
    sourceHandle: 'b',
    target: '9-1',
    targetHandle: 't',
    id: 'reactflow__edge-6b-9-1t',
    selected: false,
  },
  {
    source: '9-1',
    sourceHandle: 'b',
    target: '9-2',
    targetHandle: 't',
    id: 'reactflow__edge-9-1b-9-2t',
    selected: false,
  },
  {
    source: '6',
    sourceHandle: 'b',
    target: '10',
    targetHandle: 't',
    id: 'reactflow__edge-6b-10t',
    selected: false,
  },
  {
    source: '7',
    sourceHandle: 'b',
    target: '11',
    targetHandle: 't',
    id: 'reactflow__edge-7b-11t',
    selected: false,
  },
  {
    source: '7',
    sourceHandle: 'b',
    target: '12',
    targetHandle: 't',
    id: 'reactflow__edge-7b-12t',
    selected: false,
  },
  {
    source: '8',
    sourceHandle: 'b',
    target: '13-1',
    targetHandle: 't',
    id: 'reactflow__edge-8b-13-1t',
    selected: false,
  },
  {
    source: '13-1',
    sourceHandle: 'b',
    target: '13-2',
    targetHandle: 't',
    id: 'reactflow__edge-13-1b-13-2t',
    selected: false,
  },
  {
    source: '8',
    sourceHandle: 'b',
    target: '14',
    targetHandle: 't',
    id: 'reactflow__edge-8b-14t',
    selected: false,
  },
  {
    source: '18',
    sourceHandle: 'b',
    target: '19-1',
    targetHandle: 't',
    id: 'reactflow__edge-18b-19-1t',
    selected: false,
  },
  {
    source: '18',
    sourceHandle: 'b',
    target: '19-2',
    targetHandle: 't',
    id: 'reactflow__edge-18b-19-2t',
    selected: false,
  },
  {
    source: '20',
    sourceHandle: 'b',
    target: '21-1',
    targetHandle: 't',
    id: 'reactflow__edge-20b-21-1t',
    selected: false,
  },
  {
    source: '21-1',
    sourceHandle: 'b',
    target: '21-2',
    targetHandle: 't',
    id: 'reactflow__edge-21-1b-21-2t',
    selected: false,
  },
  {
    source: '20',
    sourceHandle: 'b',
    target: '21-3',
    targetHandle: 't',
    id: 'reactflow__edge-20b-21-3t',
    selected: false,
  },
  {
    source: '21-3',
    sourceHandle: 'b',
    target: '21-4',
    targetHandle: 't',
    id: 'reactflow__edge-21-3b-21-4t',
    selected: false,
  },
];

export const DetailWrapper = styled.div`
  width: 942px;
  height: 800px;

  .react-flow__node-default {
    border: 1px solid var(--colors-brand-500);
    border-radius: var(--borders-radius-base);
    background-color: ${({ theme }) => theme.bgColor};
  }
  button {
    background-color: ${({ theme: { isDark } }) =>
      isDark ? 'rgba(46, 52, 64, 1)' : 'var(--colors-white-500)'};
    border-bottom: 1px solid
      ${({ theme: { isDark } }) => (isDark ? 'var(--colors-black-100)' : '#eeeeee')};
    :hover {
      background-color: ${({ theme: { isDark } }) => (isDark ? 'var(--colors-black-200)' : null)};
    }
    svg {
      fill: ${({ theme: { textColor } }) => textColor};
    }
  }
`;

const FERoadmap = () => {
  const nodeTypes = useMemo(() => ({ default: CommonNode }), []);

  return (
    <DetailWrapper>
      <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView>
        <Controls />
      </ReactFlow>
    </DetailWrapper>
  );
};

export default FERoadmap;
